name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc clang lld llvm python3 bc bison flex pkg-config cpio gzip qemu-system libelf-dev
          cargo install --locked --version 0.65.1 bindgen-cli
      - name: Setup project (Submodules & Rust)
        run: make setup

      - name: Build Kernel, Rootfs and Modules
        run: make build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: woc-build-outputs
          path: |
            linux/arch/x86_64/boot/bzImage
            busybox/rootfs.img
            src/*.ko
